"""Letter — the central business entity: one piece of incoming correspondence.

Phase 4B finalized six business decisions on top of the Phase 2/4A shape
of this model — see docs/architecture/letter-registry.md §2 for the full
reasoning behind each, only summarized here:

`recipient_department_id` (renamed from the ambiguous `department_id`,
migration 48ec742d9e8f) is the department-isolation boundary — the field
`app/services/authorization.py:assert_department_access` is always called
against for a Letter. `source_department_id` is a *separate*, optional
field and carries no authorization meaning — an external sender has no
LRS account and isn't part of the role/department hierarchy at all.

`source_name` (renamed from `received_from`) is the required baseline
representation of who/where a letter came from; `source_department_id` is
an optional structured cross-reference, populated only when the source
happens to be an LRS-registered department. The system must never force
every source into a department FK (product owner's own wording) — many
incoming letters originate from organizations LRS has no record of.

`sender_name`/`sender_designation`/`sender_department` are required;
`sender_address` is deliberately optional ("the physical letter may not
provide one"). `sender_department` is intentionally a separate free-text
field from `source_department_id`/`source_name`, even though the two
often describe the same real-world department — the finalized decisions
list both as distinct fields rather than merging them; see the
architecture doc for the acknowledged overlap, not silently resolved
here.

`reference_number` is required, manually entered, and no format is
imposed — never auto-generated by this system. It is deliberately **not**
constrained unique at the database level (constraint removed by
migration `c887ab35e4a3`, a Phase 4B hardening finding): the business
confirmed reference numbers "must be unique" but never confirmed the
*scope* — globally, per receiving department, per source, per year are
all still open, and a real multi-department registry can easily have two
departments each issuing their own overlapping numbering. Enforcing a
guessed scope (global was the first guess, tried and reverted) risks
rejecting legitimate real-world duplicates. See
docs/architecture/letter-registry.md §2.3/§12, PENDING BUSINESS
CLARIFICATION. It is, however, indexed (`ix_letters_reference_number`,
migration `9fa970ffa560`, Phase 4C) — a plain, non-unique B-tree index,
added because reference-number search is a real requirement, not because
uniqueness returned.

`category_id`/`classification_id` remain nullable — neither the Phase 4A
nor Phase 4B decisions confirmed that every letter must have one assigned
at creation time; only *which* categories are valid (exactly three,
seeded by the same migration) and classification's *behavior* (see
Classification's own docstring for `restricts_access`) were finalized.

"Delete" is archival (`status -> ARCHIVED`), not physical deletion —
unchanged from Phase 2's original decision, which nothing in Phase 4B
asked to reopen. Letters are never physically deleted in normal
operation.

Phase 6A (docs/architecture/correspondence.md) adds correspondence
direction/diary tracking on top of the above, without changing any
existing column's meaning:

`direction` (`LetterDirection`, NOT NULL, `server_default 'INCOMING'`) —
every letter recorded before this phase already represented "something
that arrived here and we recorded it," i.e. `INCOMING`; the default
backfills every historical row with its own true, unchanged meaning, not
a guess. `OUTGOING` is the new case a department uses to record
correspondence it is sending elsewhere.

`dispatch_department_id` (nullable FK to `departments`) — the destination
department for an `OUTGOING` letter, required by the service layer (not a
DB constraint) exactly when `direction == OUTGOING` and forbidden
otherwise. Unlike `source_department_id`, this field *does* carry
authorization meaning, but only for one narrow, additive operation: the
new `assert_dispatch_recipient_access` (`app/services/authorization.py`)
that gates the "record incoming correspondence" action. It plays no part
in `assert_letter_access`/`letter_visibility_filter` — `recipient_department_id`
remains the one and only ownership/visibility boundary for every letter,
outgoing or incoming, exactly as before this phase.

`diary_number` (nullable string) — the operational, human-facing
identifier the supervisor calls out as the practical unique reference in
real correspondence, deliberately separate from `reference_number`
(manually entered, never confirmed unique in any scope — see this
module's own note above and docs/architecture/letter-registry.md §2.3/
§12, still unresolved and untouched by this phase). Auto-generated at
creation time via `LetterNumberSequence`, scoped per
`(recipient_department_id, direction)` — never client-supplied, never
backfilled onto historical rows (`NULL` there, by design, not an
oversight — see docs/architecture/correspondence.md §8).

`recorded_from_letter_id` (nullable, self-referential FK) — set only on
an `INCOMING` letter that was auto-created by the destination
department's "Record" action against an `OUTGOING` letter dispatched to
it; points at that `OUTGOING` letter. A partial unique index
(`__table_args__` below) enforces at the database level that a given
`OUTGOING` letter can be recorded into at most one `INCOMING` letter —
the actual duplicate-protection guarantee behind Phase 6A's "Record"
action, not merely a service-layer check.

`continuation_of_letter_id` (nullable, self-referential FK) — set on a
new letter that is a response/continuation of a prior one. Deliberately
not unique: a department may send more than one follow-up referencing
the same original. A simple self-reference, not a separate correspondence-
thread subsystem, per this phase's own explicit instruction.

`received_at` is deliberately reused, not duplicated, for `OUTGOING`
letters too — it represents "the date this correspondence record
pertains to" (received, for `INCOMING`; dispatched, for `OUTGOING`)
rather than gaining a parallel `dispatched_at` column that would say the
same thing under a different name. See
docs/architecture/correspondence.md §5 for the full reasoning.
"""

import uuid
from datetime import datetime
from typing import TYPE_CHECKING, List, Optional

from sqlalchemy import DateTime, ForeignKey, Index, String, Text
from sqlalchemy.dialects.postgresql import UUID
from sqlalchemy.orm import Mapped, mapped_column, relationship

from app.database.base import Base
from app.models.enums import (
    LetterDirection,
    LetterStatus,
    letter_direction_enum,
    letter_status_enum,
)
from app.models.mixins import TimestampMixin, UUIDPrimaryKeyMixin

if TYPE_CHECKING:
    from app.models.category import Category
    from app.models.classification import Classification
    from app.models.department import Department
    from app.models.designation import Designation
    from app.models.letter_document import LetterDocument
    from app.models.notification import Notification
    from app.models.user import User


class Letter(Base, UUIDPrimaryKeyMixin, TimestampMixin):
    __tablename__ = "letters"

    reference_number: Mapped[str] = mapped_column(String(255), nullable=False, index=True)

    recipient_department_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True),
        ForeignKey("departments.id", ondelete="RESTRICT"),
        nullable=False,
        index=True,
    )

    source_name: Mapped[str] = mapped_column(String(500), nullable=False)
    source_department_id: Mapped[Optional[uuid.UUID]] = mapped_column(
        UUID(as_uuid=True),
        ForeignKey("departments.id", ondelete="RESTRICT"),
        nullable=True,
        index=True,
    )
    source_location: Mapped[Optional[str]] = mapped_column(String(255), nullable=True)

    sender_name: Mapped[str] = mapped_column(String(255), nullable=False)
    # `sender_designation` remains the required, free-text historical
    # snapshot it always was (Phase 4B) — unchanged by Phase 5H.
    # `designation_id` is a new, nullable structured reference: when set,
    # `LetterService` copies the referenced Designation's *current* name
    # into `sender_designation` at write time — the two are never
    # expected to independently drift for a letter recorded through the
    # new dropdown, but `sender_designation` is never re-derived at read
    # time, so an existing letter's snapshot survives unchanged even if
    # `designation_id`'s target is later renamed or deactivated. See
    # docs/architecture/source-designation.md §8.
    sender_designation: Mapped[str] = mapped_column(String(255), nullable=False)
    designation_id: Mapped[Optional[uuid.UUID]] = mapped_column(
        UUID(as_uuid=True),
        ForeignKey("designations.id", ondelete="RESTRICT"),
        nullable=True,
        index=True,
    )
    sender_department: Mapped[str] = mapped_column(String(255), nullable=False)
    sender_address: Mapped[Optional[str]] = mapped_column(Text, nullable=True)

    subject: Mapped[Optional[str]] = mapped_column(String(500), nullable=True, index=True)
    reason: Mapped[Optional[str]] = mapped_column(Text, nullable=True)
    category_id: Mapped[Optional[uuid.UUID]] = mapped_column(
        UUID(as_uuid=True),
        ForeignKey("categories.id", ondelete="RESTRICT"),
        nullable=True,
        index=True,
    )
    classification_id: Mapped[Optional[uuid.UUID]] = mapped_column(
        UUID(as_uuid=True),
        ForeignKey("classifications.id", ondelete="RESTRICT"),
        nullable=True,
        index=True,
    )
    received_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), nullable=False, index=True
    )
    recorded_by: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True),
        ForeignKey("users.id", ondelete="RESTRICT"),
        nullable=False,
        index=True,
    )
    text_content: Mapped[Optional[str]] = mapped_column(Text, nullable=True)
    status: Mapped[LetterStatus] = mapped_column(
        letter_status_enum, nullable=False, default=LetterStatus.ACTIVE, index=True
    )

    direction: Mapped[LetterDirection] = mapped_column(
        letter_direction_enum,
        nullable=False,
        default=LetterDirection.INCOMING,
        server_default=LetterDirection.INCOMING.value,
        index=True,
    )
    dispatch_department_id: Mapped[Optional[uuid.UUID]] = mapped_column(
        UUID(as_uuid=True),
        ForeignKey("departments.id", ondelete="RESTRICT"),
        nullable=True,
        index=True,
    )
    diary_number: Mapped[Optional[str]] = mapped_column(String(50), nullable=True)
    recorded_from_letter_id: Mapped[Optional[uuid.UUID]] = mapped_column(
        UUID(as_uuid=True),
        ForeignKey("letters.id", ondelete="RESTRICT"),
        nullable=True,
    )
    continuation_of_letter_id: Mapped[Optional[uuid.UUID]] = mapped_column(
        UUID(as_uuid=True),
        ForeignKey("letters.id", ondelete="RESTRICT"),
        nullable=True,
        index=True,
    )

    recipient_department: Mapped["Department"] = relationship(
        back_populates="letters", foreign_keys=[recipient_department_id]
    )
    source_department: Mapped[Optional["Department"]] = relationship(
        foreign_keys=[source_department_id]
    )
    dispatch_department: Mapped[Optional["Department"]] = relationship(
        foreign_keys=[dispatch_department_id]
    )
    recorded_from_letter: Mapped[Optional["Letter"]] = relationship(
        remote_side="Letter.id", foreign_keys=[recorded_from_letter_id]
    )
    continuation_of_letter: Mapped[Optional["Letter"]] = relationship(
        remote_side="Letter.id", foreign_keys=[continuation_of_letter_id]
    )
    category: Mapped[Optional["Category"]] = relationship(back_populates="letters")
    designation: Mapped[Optional["Designation"]] = relationship(back_populates="letters")
    classification: Mapped[Optional["Classification"]] = relationship(
        back_populates="letters"
    )
    recorded_by_user: Mapped["User"] = relationship(
        back_populates="letters_recorded", foreign_keys=[recorded_by]
    )
    # See docs/database/schema.md, "ORM deletion behavior" — cascade="all,
    # delete-orphan" (not passive_deletes) because each LetterDocument is a
    # true owned child with no life of its own; SQLAlchemy disallows
    # combining the two.
    documents: Mapped[List["LetterDocument"]] = relationship(
        back_populates="letter", cascade="all, delete-orphan"
    )
    notifications: Mapped[List["Notification"]] = relationship(
        back_populates="letter", passive_deletes="all"
    )

    __table_args__ = (
        # No uniqueness constraint on reference_number — see this module's
        # docstring and migration c887ab35e4a3.
        # Supports the primary access pattern: "this department's letters,
        # ordered by receipt date" — recipient_department_id, not source.
        Index(
            "ix_letters_recipient_department_received_at",
            "recipient_department_id",
            "received_at",
        ),
        # The actual, database-enforced duplicate-protection guarantee
        # behind the "Record" action (Phase 6A) — a partial unique index
        # (not a plain UniqueConstraint) because most letters have
        # recorded_from_letter_id = NULL, and PostgreSQL already treats
        # multiple NULLs as distinct; this index only ever needs to
        # constrain the non-NULL subset. See
        # docs/architecture/correspondence.md §7.
        Index(
            "uq_letters_recorded_from_letter_id",
            "recorded_from_letter_id",
            unique=True,
            postgresql_where=recorded_from_letter_id.isnot(None),
        ),
    )

    def __repr__(self) -> str:  # pragma: no cover - debug convenience only
        return (
            f"<Letter id={self.id} reference_number={self.reference_number!r} "
            f"recipient_department_id={self.recipient_department_id} status={self.status}>"
        )
