"""Letter — the central business entity: one piece of incoming correspondence.

Phase 4B finalized six business decisions on top of the Phase 2/4A shape
of this model — see docs/architecture/letter-registry.md §2 for the full
reasoning behind each, only summarized here:

`recipient_department_id` (renamed from the ambiguous `department_id`,
migration 48ec742d9e8f) is the department-isolation boundary — the field
`app/services/authorization.py:assert_department_access` is always called
against for a Letter. `source_department_id` is a *separate*, optional
field and carries no authorization meaning — an external sender has no
LRS account and isn't part of the role/department hierarchy at all.

`source_name` (renamed from `received_from`) is the required baseline
representation of who/where a letter came from; `source_department_id` is
an optional structured cross-reference, populated only when the source
happens to be an LRS-registered department. The system must never force
every source into a department FK (product owner's own wording) — many
incoming letters originate from organizations LRS has no record of.

`sender_name`/`sender_designation`/`sender_department` are required;
`sender_address` is deliberately optional ("the physical letter may not
provide one"). `sender_department` is intentionally a separate free-text
field from `source_department_id`/`source_name`, even though the two
often describe the same real-world department — the finalized decisions
list both as distinct fields rather than merging them; see the
architecture doc for the acknowledged overlap, not silently resolved
here.

`reference_number` is required, manually entered, and no format is
imposed — never auto-generated by this system. It is deliberately **not**
constrained unique at the database level (constraint removed by
migration `c887ab35e4a3`, a Phase 4B hardening finding): the business
confirmed reference numbers "must be unique" but never confirmed the
*scope* — globally, per receiving department, per source, per year are
all still open, and a real multi-department registry can easily have two
departments each issuing their own overlapping numbering. Enforcing a
guessed scope (global was the first guess, tried and reverted) risks
rejecting legitimate real-world duplicates. See
docs/architecture/letter-registry.md §2.3/§12, PENDING BUSINESS
CLARIFICATION.

`category_id`/`classification_id` remain nullable — neither the Phase 4A
nor Phase 4B decisions confirmed that every letter must have one assigned
at creation time; only *which* categories are valid (exactly three,
seeded by the same migration) and classification's *behavior* (see
Classification's own docstring for `restricts_access`) were finalized.

"Delete" is archival (`status -> ARCHIVED`), not physical deletion —
unchanged from Phase 2's original decision, which nothing in Phase 4B
asked to reopen. Letters are never physically deleted in normal
operation.
"""

import uuid
from datetime import datetime
from typing import TYPE_CHECKING, List, Optional

from sqlalchemy import DateTime, ForeignKey, Index, String, Text
from sqlalchemy.dialects.postgresql import UUID
from sqlalchemy.orm import Mapped, mapped_column, relationship

from app.database.base import Base
from app.models.enums import LetterStatus, letter_status_enum
from app.models.mixins import TimestampMixin, UUIDPrimaryKeyMixin

if TYPE_CHECKING:
    from app.models.category import Category
    from app.models.classification import Classification
    from app.models.department import Department
    from app.models.letter_document import LetterDocument
    from app.models.notification import Notification
    from app.models.user import User


class Letter(Base, UUIDPrimaryKeyMixin, TimestampMixin):
    __tablename__ = "letters"

    reference_number: Mapped[str] = mapped_column(String(255), nullable=False)

    recipient_department_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True),
        ForeignKey("departments.id", ondelete="RESTRICT"),
        nullable=False,
        index=True,
    )

    source_name: Mapped[str] = mapped_column(String(500), nullable=False)
    source_department_id: Mapped[Optional[uuid.UUID]] = mapped_column(
        UUID(as_uuid=True),
        ForeignKey("departments.id", ondelete="RESTRICT"),
        nullable=True,
        index=True,
    )
    source_location: Mapped[Optional[str]] = mapped_column(String(255), nullable=True)

    sender_name: Mapped[str] = mapped_column(String(255), nullable=False)
    sender_designation: Mapped[str] = mapped_column(String(255), nullable=False)
    sender_department: Mapped[str] = mapped_column(String(255), nullable=False)
    sender_address: Mapped[Optional[str]] = mapped_column(Text, nullable=True)

    subject: Mapped[Optional[str]] = mapped_column(String(500), nullable=True, index=True)
    reason: Mapped[Optional[str]] = mapped_column(Text, nullable=True)
    category_id: Mapped[Optional[uuid.UUID]] = mapped_column(
        UUID(as_uuid=True),
        ForeignKey("categories.id", ondelete="RESTRICT"),
        nullable=True,
        index=True,
    )
    classification_id: Mapped[Optional[uuid.UUID]] = mapped_column(
        UUID(as_uuid=True),
        ForeignKey("classifications.id", ondelete="RESTRICT"),
        nullable=True,
        index=True,
    )
    received_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), nullable=False, index=True
    )
    recorded_by: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True),
        ForeignKey("users.id", ondelete="RESTRICT"),
        nullable=False,
        index=True,
    )
    text_content: Mapped[Optional[str]] = mapped_column(Text, nullable=True)
    status: Mapped[LetterStatus] = mapped_column(
        letter_status_enum, nullable=False, default=LetterStatus.ACTIVE, index=True
    )

    recipient_department: Mapped["Department"] = relationship(
        back_populates="letters", foreign_keys=[recipient_department_id]
    )
    source_department: Mapped[Optional["Department"]] = relationship(
        foreign_keys=[source_department_id]
    )
    category: Mapped[Optional["Category"]] = relationship(back_populates="letters")
    classification: Mapped[Optional["Classification"]] = relationship(
        back_populates="letters"
    )
    recorded_by_user: Mapped["User"] = relationship(
        back_populates="letters_recorded", foreign_keys=[recorded_by]
    )
    # See docs/database/schema.md, "ORM deletion behavior" — cascade="all,
    # delete-orphan" (not passive_deletes) because each LetterDocument is a
    # true owned child with no life of its own; SQLAlchemy disallows
    # combining the two.
    documents: Mapped[List["LetterDocument"]] = relationship(
        back_populates="letter", cascade="all, delete-orphan"
    )
    notifications: Mapped[List["Notification"]] = relationship(
        back_populates="letter", passive_deletes="all"
    )

    __table_args__ = (
        # No uniqueness constraint on reference_number — see this module's
        # docstring and migration c887ab35e4a3.
        # Supports the primary access pattern: "this department's letters,
        # ordered by receipt date" — recipient_department_id, not source.
        Index(
            "ix_letters_recipient_department_received_at",
            "recipient_department_id",
            "received_at",
        ),
    )

    def __repr__(self) -> str:  # pragma: no cover - debug convenience only
        return (
            f"<Letter id={self.id} reference_number={self.reference_number!r} "
            f"recipient_department_id={self.recipient_department_id} status={self.status}>"
        )
