"""core schema: departments, users, authorizations, categories, classifications, letters, documents, notifications, audit logs

Phase 2 initial schema. Hand-written (not autogenerated) because no local
PostgreSQL instance was available to autogenerate against in this
environment — see docs/database/README.md, "Applying this migration
locally" and docs/PROJECT_STATUS.md, "Known Limitations". The table/column/
constraint/index definitions below were derived directly from the
SQLAlchemy models in app/models/ and cross-checked against
`Base.metadata` (see the model docstrings for the reasoning behind
individual FK ondelete behaviors, nullability, and index choices).

Revision ID: 3da4b7ee8167
Revises:
Create Date: 2026-08-17 01:22:38.095217
"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "3da4b7ee8167"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


# Shared PostgreSQL ENUM types. `create_type=False` on the reused
# `active_status` type stops SQLAlchemy from re-issuing `CREATE TYPE` once
# per table that uses it — it is created explicitly, once, below.
active_status_enum = postgresql.ENUM(
    "ACTIVE", "INACTIVE", name="active_status", create_type=False
)
user_role_enum = postgresql.ENUM(
    "SYSTEM_ADMIN", "ADMIN", "USER", name="user_role", create_type=False
)
user_status_enum = postgresql.ENUM(
    "PENDING_APPROVAL", "ACTIVE", "DEACTIVATED", name="user_status", create_type=False
)
authorization_status_enum = postgresql.ENUM(
    "ACTIVE", "USED", "REVOKED", name="authorization_status", create_type=False
)
letter_status_enum = postgresql.ENUM(
    "ACTIVE", "ARCHIVED", name="letter_status", create_type=False
)


def upgrade() -> None:
    bind = op.get_bind()
    active_status_enum.create(bind, checkfirst=True)
    user_role_enum.create(bind, checkfirst=True)
    user_status_enum.create(bind, checkfirst=True)
    authorization_status_enum.create(bind, checkfirst=True)
    letter_status_enum.create(bind, checkfirst=True)

    op.create_table(
        "departments",
        sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("code", sa.String(length=50), nullable=True),
        sa.Column("status", active_status_enum, nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.func.now(),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.func.now(),
            nullable=False,
        ),
        sa.UniqueConstraint("name", name="uq_departments_name"),
        sa.UniqueConstraint("code", name="uq_departments_code"),
    )

    op.create_table(
        "categories",
        sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("status", active_status_enum, nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.func.now(),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.func.now(),
            nullable=False,
        ),
        sa.UniqueConstraint("name", name="uq_categories_name"),
    )
    op.create_index("ix_categories_status", "categories", ["status"])

    op.create_table(
        "classifications",
        sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("status", active_status_enum, nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.func.now(),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.func.now(),
            nullable=False,
        ),
        sa.UniqueConstraint("name", name="uq_classifications_name"),
    )
    op.create_index("ix_classifications_status", "classifications", ["status"])

    op.create_table(
        "users",
        sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True),
        sa.Column("full_name", sa.String(length=255), nullable=False),
        sa.Column("email", sa.String(length=320), nullable=False),
        sa.Column("password_hash", sa.String(length=255), nullable=False),
        sa.Column("role", user_role_enum, nullable=False),
        sa.Column("department_id", postgresql.UUID(as_uuid=True), nullable=True),
        sa.Column("status", user_status_enum, nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.func.now(),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.func.now(),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["department_id"], ["departments.id"], ondelete="RESTRICT"
        ),
        sa.CheckConstraint(
            "(role = 'SYSTEM_ADMIN' AND department_id IS NULL) OR "
            "(role IN ('ADMIN', 'USER') AND department_id IS NOT NULL)",
            name="ck_users_role_department_pairing",
        ),
    )
    op.create_index(
        "uq_users_email_lower", "users", [sa.text("lower(email)")], unique=True
    )
    op.create_index("ix_users_department_id", "users", ["department_id"])
    op.create_index("ix_users_role", "users", ["role"])
    op.create_index("ix_users_status", "users", ["status"])

    op.create_table(
        "user_authorizations",
        sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True),
        sa.Column("email", sa.String(length=320), nullable=False),
        sa.Column("department_id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("authorized_by", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("status", authorization_status_enum, nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.func.now(),
            nullable=False,
        ),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["department_id"], ["departments.id"], ondelete="RESTRICT"
        ),
        sa.ForeignKeyConstraint(["authorized_by"], ["users.id"], ondelete="RESTRICT"),
    )
    op.create_index(
        "ix_user_authorizations_email_lower",
        "user_authorizations",
        [sa.text("lower(email)")],
    )
    op.create_index(
        "ix_user_authorizations_department_id", "user_authorizations", ["department_id"]
    )
    op.create_index(
        "ix_user_authorizations_authorized_by", "user_authorizations", ["authorized_by"]
    )
    op.create_index("ix_user_authorizations_status", "user_authorizations", ["status"])

    op.create_table(
        "letters",
        sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True),
        sa.Column("department_id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("received_from", sa.String(length=500), nullable=False),
        sa.Column("subject", sa.String(length=500), nullable=True),
        sa.Column("reason", sa.Text(), nullable=True),
        sa.Column("category_id", postgresql.UUID(as_uuid=True), nullable=True),
        sa.Column("classification_id", postgresql.UUID(as_uuid=True), nullable=True),
        sa.Column("received_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("recorded_by", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("text_content", sa.Text(), nullable=True),
        sa.Column("status", letter_status_enum, nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.func.now(),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.func.now(),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["department_id"], ["departments.id"], ondelete="RESTRICT"
        ),
        sa.ForeignKeyConstraint(["category_id"], ["categories.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(
            ["classification_id"], ["classifications.id"], ondelete="RESTRICT"
        ),
        sa.ForeignKeyConstraint(["recorded_by"], ["users.id"], ondelete="RESTRICT"),
    )
    op.create_index("ix_letters_department_id", "letters", ["department_id"])
    op.create_index("ix_letters_subject", "letters", ["subject"])
    op.create_index("ix_letters_category_id", "letters", ["category_id"])
    op.create_index("ix_letters_classification_id", "letters", ["classification_id"])
    op.create_index("ix_letters_received_at", "letters", ["received_at"])
    op.create_index("ix_letters_recorded_by", "letters", ["recorded_by"])
    op.create_index("ix_letters_status", "letters", ["status"])
    op.create_index(
        "ix_letters_department_received_at",
        "letters",
        ["department_id", "received_at"],
    )

    op.create_table(
        "letter_documents",
        sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True),
        sa.Column("letter_id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("document_type", sa.String(length=50), nullable=True),
        sa.Column("original_filename", sa.String(length=500), nullable=False),
        sa.Column("storage_path", sa.String(length=1000), nullable=False),
        sa.Column("file_size", sa.BigInteger(), nullable=True),
        sa.Column("mime_type", sa.String(length=255), nullable=True),
        sa.Column("uploaded_by", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column(
            "uploaded_at",
            sa.DateTime(timezone=True),
            server_default=sa.func.now(),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["letter_id"], ["letters.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["uploaded_by"], ["users.id"], ondelete="RESTRICT"),
    )
    op.create_index("ix_letter_documents_letter_id", "letter_documents", ["letter_id"])

    op.create_table(
        "notifications",
        sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True),
        sa.Column("recipient_user_id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("letter_id", postgresql.UUID(as_uuid=True), nullable=True),
        sa.Column("notification_type", sa.String(length=100), nullable=False),
        sa.Column("message", sa.Text(), nullable=False),
        sa.Column("is_read", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.func.now(),
            nullable=False,
        ),
        sa.Column("read_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["recipient_user_id"], ["users.id"], ondelete="RESTRICT"
        ),
        sa.ForeignKeyConstraint(["letter_id"], ["letters.id"], ondelete="CASCADE"),
    )
    op.create_index(
        "ix_notifications_recipient_is_read",
        "notifications",
        ["recipient_user_id", "is_read"],
    )
    op.create_index(
        "ix_notifications_recipient_user_id", "notifications", ["recipient_user_id"]
    )
    op.create_index("ix_notifications_letter_id", "notifications", ["letter_id"])

    op.create_table(
        "audit_logs",
        sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True),
        sa.Column("user_id", postgresql.UUID(as_uuid=True), nullable=True),
        sa.Column("action", sa.String(length=100), nullable=False),
        sa.Column("entity_type", sa.String(length=100), nullable=False),
        sa.Column("entity_id", postgresql.UUID(as_uuid=True), nullable=True),
        sa.Column("old_values", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("new_values", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.func.now(),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="SET NULL"),
    )
    op.create_index("ix_audit_logs_user_id", "audit_logs", ["user_id"])
    op.create_index("ix_audit_logs_entity_type", "audit_logs", ["entity_type"])
    op.create_index(
        "ix_audit_logs_entity_type_entity_id",
        "audit_logs",
        ["entity_type", "entity_id"],
    )
    op.create_index("ix_audit_logs_created_at", "audit_logs", ["created_at"])


def downgrade() -> None:
    op.drop_table("audit_logs")
    op.drop_table("notifications")
    op.drop_table("letter_documents")
    op.drop_table("letters")
    op.drop_table("user_authorizations")
    op.drop_table("users")
    op.drop_table("classifications")
    op.drop_table("categories")
    op.drop_table("departments")

    bind = op.get_bind()
    letter_status_enum.drop(bind, checkfirst=True)
    authorization_status_enum.drop(bind, checkfirst=True)
    user_status_enum.drop(bind, checkfirst=True)
    user_role_enum.drop(bind, checkfirst=True)
    active_status_enum.drop(bind, checkfirst=True)
